import Head from "next/head";
import Home from "../pages/Home/index";
export default function APP() {
  return (
    <div style={{ display: "flex", justifyContent: "center" }}>
      <Head>
        <title>رفيق طريق</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/LOGO.svg" />
      </Head>
      <Home />
    </div>
  );
}
